sudo: required
services: 
  - docker

before_install:
  - docker build -t krishnapriya2569/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true krishnapriya2569/docker-react npm run test